import dotenv from 'dotenv';
dotenv.config()

export const {
    APP_PORT,
    APP_URL,
    DEBUG_MODE,
    MONGO_URL,
    JWT_SECRET,
    JWT_EXPIRES_IN,
    SALT_FACTOR,
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    STUDENT_CALLBACK_URL_LOGIN,
    STUDENT_CALLBACK_URL_REGISTER,
    TUTOR_CALLBACK_URL_LOGIN,
    TUTOR_CALLBACK_URL_REGISTER,
    CLIENT_ID,
    FAST2SMS,
    TWILIO_ACCOUNT_SID,
    TWILIO_AUTH_TOKEN,
    GOOGLE_MAIL,
    GOOGLE_PASSWORD,
    AWS_ACCESS_KEY,
    AWS_SECRET_KEY,
    SENDER_EMAIL,
    STRIPE_SECRETE_KEY
} = process.env;